import 'package:equatable/equatable.dart';

class Employee extends Equatable {
  /// Autogenerated id based on DateTime
  final int id;
  final String? employeeName;
  final String? employeeRole;
  final DateTime? startDate;
  final DateTime? endDate;

  /// Public constructor
  Employee({
    this.employeeName,
    this.employeeRole,
    this.startDate,
    this.endDate,
  }) : id = DateTime.now().millisecondsSinceEpoch;

  /// Internal constructor to edit all fields
  const Employee._({
    this.employeeName,
    this.employeeRole,
    this.startDate,
    this.endDate,
    required this.id,
  });

  Employee copyWith({
    String? employeeName,
    String? employeeRole,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      Employee._(
        employeeName: employeeName ?? this.employeeName,
        employeeRole: employeeRole ?? this.employeeRole,
        startDate: startDate ?? this.startDate,
        endDate: endDate ?? this.endDate,
        id: id,
      );

  factory Employee.fromJson(Map<String, dynamic> json) => Employee(
        employeeName: json["employeeName"],
        employeeRole: json["employeeRole"],
        startDate: json["startDate"] == null
            ? null
            : DateTime.parse(json["startDate"]),
        endDate:
            json["endDate"] == null ? null : DateTime.parse(json["endDate"]),
      );

  Map<String, dynamic> toJson() => {
        "employeeName": employeeName,
        "employeeRole": employeeRole,
        "startDate": startDate?.toIso8601String(),
        "endDate": endDate?.toIso8601String(),
        "id": id,
      };

  @override
  List<Object?> get props => [id];
}
